name: pythonGPU
channels:
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0=gpu
  - absl-py=0.10.0=py38_0
  - aiohttp=3.6.3=py38he774522_0
  - argon2-cffi=20.1.0=py38he774522_1
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38_0
  - async_generator=1.10=py_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - blinker=1.4=py38_0
  - brotlipy=0.7.0=py38he774522_1000
  - ca-certificates=2020.12.8=haa95532_0
  - cachetools=4.1.1=py_0
  - certifi=2020.12.5=py38haa95532_0
  - cffi=1.14.3=py38h7a1dbc1_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - console_shortcut=0.1.1=4
  - cryptography=3.1.1=py38h7a1dbc1_0
  - cycler=0.10.0=py38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - freetype=2.10.4=hd328e21_0
  - gast=0.4.0=py_0
  - google-auth=1.22.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py38he7da953_0
  - h5py=2.10.0=py38h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=vc14hc45fdbb_0
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.19.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=vc14h4d7706e_1
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py38haa95532_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - keras-applications=1.0.8=py_1
  - keras-base=2.4.3=py_0
  - keras-gpu=2.4.3=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py38h74a9793_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.13.0.1=h200bbdf_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=hf4a77e7_3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.2=py38_0
  - markupsafe=1.1.1=py38he774522_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py38hba9282a_0
  - mistune=0.8.4=py38he774522_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h196d8e1_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - multidict=4.7.6=py38he774522_1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - notebook=6.1.5=py38haa95532_0
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1i=h2bbff1b_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandas=1.1.3=py38ha925a31_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.3=py38haa95532_1
  - parso=0.8.1=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.0.0=py38hca74424_0
  - pip=20.2.4=py38_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - protobuf=3.13.0.1=py38ha925a31_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.7.3=pyhd3eb1b0_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyreadline=2.1=py38_1
  - pyrsistent=0.17.3=py38he774522_0
  - pysocks=1.7.1=py38_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pywin32=227=py38he774522_1
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.3.1=py38he774522_0
  - pyzmq=20.0.0=py38hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scipy=1.5.2=py38h14eb087_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=50.3.0=py38h9490d1a_1
  - sip=4.19.24=py38ha925a31_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.3.0=mkl_py38h8557ec7_0
  - tensorflow-base=2.3.0=eigen_py38h75a453f_0
  - tensorflow-estimator=2.3.0=pyheb71bc4_0
  - tensorflow-gpu=2.3.0=he13fc11_0
  - termcolor=1.1.0=py38_1
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=he774522_0
  - tornado=6.0.4=py38he774522_1
  - traitlets=5.0.5=py_0
  - urllib3=1.25.11=py_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38he774522_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.1.7=vc14h4cb57cf_1
  - yarl=1.6.2=py38he774522_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.4=ha9fde0e_3
  - pip:
    - audioread==2.1.9
    - beautifulsoup4==4.9.3
    - docopt==0.6.2
    - flask==1.1.2
    - ipywidgets==7.6.2
    - itsdangerous==1.1.0
    - joblib==1.0.0
    - js2py==0.70
    - jupyterlab-widgets==1.0.0
    - librosa==0.8.0
    - llvmlite==0.31.0
    - opencv-python==4.4.0.46
    - pipwin==0.5.0
    - pocketsphinx==0.1.15
    - pyaudio==0.2.11
    - pyjsparser==2.7.1
    - pyprind==2.11.2
    - pysmartdl==1.3.4
    - resampy==0.2.2
    - soundfile==0.10.3.post1
    - soupsieve==2.1
    - threadpoolctl==2.1.0
    - tzlocal==2.1
    - vosk==0.3.7
    - widgetsnbextension==3.5.1
prefix: C:\Users\mingb\anaconda3\envs\pythonGPU

